name: Build APK

on:
  push:
    branches:
      - master  # Change to your target branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Specify Java distribution
          java-version: '17'  # Specify your Java version

      - name: Build APK
        run: ./gradlew assembleRelease  # Adjust if you need debug APK
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vremia-apk
          path: app/build/outputs/apk/release/vremia-release.apk  # Adjust path as necessary
